# Color palette
palette = 'catppuccin_mocha'

[git_branch]
symbol = "🌱 "

[package]
display_private = true

[custom.giturl-pwsh]
disabled = false
description = "Display symbol for remote Git server (pwsh)"
command = """
$gitRemote = git ls-remote --get-url
$symbol = ' ' # If no Git Remote is returned.
switch -regex ($gitRemote) {\
    'github'    { $symbol = ' ' }\
    'gitlab'    { $symbol = ' ' }\
    'bitbucket' { $symbol = ' ' }\
     Default    { $symbol = ' ' }\
}
echo $symbol
"""
when = "git rev-parse --is-inside-work-tree"
shell = ["pwsh", "-NoProfile", "-Command", "-"]
format = "at $output"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"